# Generated by Django 6.0.6 on 2026-06-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion_id', models.IntegerField()),
                ('domiciliario_id', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ACCIDENTE', 'Accidente'), ('ROBO', 'Robo'), ('EMERGENCIA', 'Emergencia médica'), ('OTRO', 'Otro')], default='EMERGENCIA', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'emergencias',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
