# Generated by Django 6.0.5 on 2026-06-07 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tipomaestra_options_and_more'),
        ('entregas', '0002_alter_historialestadoentrega_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoentrega',
            name='compFecha',
            field=models.DateField(blank=True, db_column='SEGU_COMP_FECHA', null=True),
        ),
        migrations.AddField(
            model_name='seguimientoentrega',
            name='compValor',
            field=models.DecimalField(blank=True, db_column='SEGU_COMP_VALOR', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='seguimientoentrega',
            name='tiempoGarantizado',
            field=models.IntegerField(blank=True, db_column='SEGU_TIEMPO_GARANTIZADO', null=True),
        ),
        migrations.AddField(
            model_name='seguimientoentrega',
            name='tipoComp',
            field=models.ForeignKey(blank=True, db_column='TIPO_COMP', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comps_seguimiento', to='core.tipomaestra'),
        ),
        migrations.AddField(
            model_name='seguimientoentrega',
            name='tipoEstadoComp',
            field=models.ForeignKey(blank=True, db_column='TIPO_ESTADO_COMP', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estados_comp_seguimiento', to='core.tipomaestra'),
        ),
    ]
