# Generated by Django 6.0.5 on 2026-06-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_cliente_options_alter_domiciliario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domiciliario',
            name='puntajeDomiciliario',
            field=models.IntegerField(db_column='DOMI_PUNTAJE', default=100),
        ),
    ]
