# Generated by Django 6.0.5 on 2026-06-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_alter_asignacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddisponible',
            name='grupoSolicitudDisponible',
            field=models.IntegerField(blank=True, db_column='SOLI_DISP_GRUPO', null=True),
        ),
    ]
